export const lgaToAreas = {
  // --- LAGOS ---
  "Eti-Osa": ["Lekki Phase 1", "Lekki Phase 2", "Ajah", "Sangotedo", "Ikoyi", "Victoria Island", "Oniru", "Ikate", "Agungi", "Lakowe", "Chevron", "Igbo Efon"],
  "Ibeju-Lekki": ["Awoyaya", "Abijo", "Eputu", "Ibeju", "Bogije", "Eleko", "Akodo", "Ibeju Town", "Orimedu"],
  "Alimosho": ["Ikotun", "Egbeda", "Idimu", "Ayobo", "Ipaja", "Akowonjo", "Gowon Estate", "Shasha", "Igando", "Isheri Olofin"],
  "Ikeja": ["Opebi", "Allen Avenue", "GRA Ikeja", "Ogba", "Alausa", "Oregun", "Anifowoshe", "Maryland Ikeja", "Computer Village"],
  "Surulere": ["Aguda", "Bode Thomas", "Adelabu", "Ijesha", "Itire", "Ojuelegba", "Lawanson", "Masha", "Kilometer 1"],
  "Lagos Mainland": ["Yaba", "Sabo", "Ebute Metta", "Alagomeji", "Adekunle", "Makoko"],
  "Agege": ["Agege", "Dopemu", "Orile Agege", "Mangoro", "Mulero", "Oko-Oba"],
  "Ajeromi-Ifelodun": ["Ajegunle", "Alayabiagba", "Tolu", "Awodi-Ora", "Wilmer"],
  "Amuwo-Odofin": ["Festac", "Mile 2", "Abule Ado", "Satellite Town", "Ago Palace", "Amuwo", "Apple Junction"],
  "Apapa": ["Apapa GRA", "Ijora", "Olodi", "Tin Can", "Liverpool", "Creek Road"],
  "Badagry": ["Badagry Town", "Ajara", "Iworo", "Seme", "Topo", "Aradagun"],
  "Epe": ["Epe Town", "Eredo", "Itoikin", "Poka", "Odo Afin"],
  "Ifako-Ijaiye": ["Ifako", "Ijaiye", "Ogba-Ijaiye", "Alakuko", "Fagba", "Iju"],
  "Ikorodu": ["Ikorodu Town", "Igbogbo", "Ijede", "Imota", "Igbogbo", "Majidun", "Odongunyan", "Isawo"],
  "Kosofe": ["Ketu", "Ojota", "Ogudu", "Mende", "Anthony", "Oworonshoki", "Ikosi", "Mile 12"],
  "Lagos Island": ["Isale Eko", "Marina", "Onikan", "Obalende", "Campos", "Idumota"],
  "Mushin": ["Mushin Olosha", "Ojuwoye", "Papa Ajao", "Idi-Oro", "Ilasamaja", "Isolo Road"],
  "Ojo": ["Ojo Town", "Okokomaiko", "Iba", "Ajangbadi", "Iyana Iba", "Alaba International"],
  "Oshodi-Isolo": ["Oshodi", "Isolo", "Ajao Estate", "Ejigbo", "Mafoluku", "Okota", "Ago Palace"],
  "Shomolu": ["Bariga", "Somolu", "Pedro", "Akoka", "Palmgrove", "Onipanu"],

  // --- RIVERS ---
  "Port Harcourt": ["GRA Phase 1", "GRA Phase 2", "GRA Phase 3", "Old GRA", "Peter Odili Road", "Trans Amadi", "D-Line", "Elekahia", "Rumuibekwe", "Artillery", "Borokiri", "Diobu", "Mile 1", "Mile 3"],
  "Obio/Akpor": ["Rumuokoro", "Rumuola", "Eliozu", "Woji", "Rumuigbo", "Choba", "Rumuodomaya", "Rumuekini", "Mgbuoba", "Rumuokwuta", "Eneka", "Rupokwu", "Ada George"],
  "Ikwerre": ["Isiokpo", "Aluu", "Omagwa", "Igwuruta", "Ubima", "Elele", "Omerelu"],
  "Eleme": ["Onne", "Eteo", "Akpajo", "Alesa", "Aleto", "Ebubu", "Ogale"],
  "Oyigbo": ["Oyigbo Town", "Afam", "Imo Gate", "Komkom", "Mirinwayi"],
  "Abua/Odual": ["Abua", "Odual", "Emago-Kugbo", "Central Abua"],
  "Ahoada East": ["Ahoada", "Ubie", "Idu Ekpeye", "Odiabidi"],
  "Ahoada West": ["Akinima", "Engenni", "Mbiama", "Okwarki"],
  "Akuku-Toru": ["Abonnema", "Obonoma", "Kula", "Ido"],
  "Andoni": ["Ngo", "Unyeada", "Ikuru Town", "Ataba"],
  "Asari-Toru": ["Buguma", "Abalama", "Krakrama", "Minama"],
  "Bonny": ["Bonny Town", "Finima", "Abonnema Wharf"],
  "Degema": ["Degema", "Bakana", "Tombia", "Bukuma", "Ke"],
  "Emohua": ["Emohua", "Rumuji", "Ibaa", "Oduoha", "Evekwu"],
  "Etche": ["Okehi", "Nihi", "Egwurugwu", "Mba", "Ndashi", "Umuechem"],
  "Gokana": ["Kpor", "Bodo", "B-Dere", "Mogho", "K-Dere"],
  "Khana": ["Bori", "Boue", "Kono", "Kaani", "Zaakpon"],
  "Ogba/Egbema/Ndoni": ["Omoku", "Egi", "Ndoni", "Usomini", "Idu"],
  "Ogu/Bolo": ["Ogu", "Bolo", "Wakama", "Ele"],
  "Okrika": ["Okrika Town", "Ogu", "Kala-Bioama", "Ogan"],
  "Omuma": ["Eberi", "Umuabali", "Ofeh"],
  "Opobo/Nkoro": ["Opobo Town", "Nkoro", "Kalaibiama"],
  "Tai": ["Saakpenwa", "Kira", "Korokoro", "Nonwa"],

  // --- FCT ---
  "Municipal Area Council": ["Wuse", "Wuse 2", "Maitama", "Asokoro", "Garki", "Garki 2", "Jabi", "Utako", "Gwarimpa", "Kubwa", "Wuye", "Jahi", "Mabushi", "Katampe", "Guzape", "Kado", "Durumi", "Karmo", "Life Camp", "Dawaki"],
  "Abaji": ["Abaji Town", "Nuku", "Gawu", "Yaba"],
  "Bwari": ["Bwari Town", "Dutse Alhaji", "Kubwa", "Usman Dam", "Mpape", "Kuduru", "Shere"],
  "Gwagwalada": ["Gwagwalada Town", "Giri", "Zuba", "Tungan Maje", "Dobi", "Ikwa"],
  "Kuje": ["Kuje Town", "Chibiri", "Gaube", "Kuchiyako", "Rubochi"],
  "Kwali": ["Kwali Town", "Yangoji", "Ashara", "Dafa", "Kilankwa"],

  // --- OYO ---
  "Afijio": ["Jobele", "Awe", "Iware", "Ilora", "Fiditi"],
  "Akinyele": ["Moniya", "Ojoo", "Ijaiye", "Alabata", "Ikereku"],
  "Atiba": ["Oyo Town", "Awe", "Agbaa", "Batake"],
  "Atisbo": ["Tede", "Ago-Are", "Irawo", "Ofiki", "Baasi"],
  "Egbeda": ["Egbeda Town", "Olodo", "Alakia", "Iyana Church", "Monatan", "Eleshin"],
  "Ibadan North": ["Bodija", "UI Area", "Agodi", "Mokola", "Sango", "Ojoo", "Samonda", "Ikolaba"],
  "Ibadan North-East": ["Iwo Road", "Agodi Gate", "Beere", "Orita Bashorun", "Ife Road"],
  "Ibadan North-West": ["Dugbe", "Onireke", "Ayeye", "Idikan"],
  "Ibadan South-East": ["Mapo", "Oja-Oba", "Felele", "Orita Challenge", "Molete"],
  "Ibadan South-West": ["Ring Road", "Oluyole", "Challenge", "Molete", "Oke-Ado", "Oke-Bola", "Apata", "Odo-Ona"],
  "Ibarapa Central": ["Igbo Ora", "Idere", "Igangan Road"],
  "Ibarapa East": ["Eruwa", "Lanlate", "Oke Oba"],
  "Ibarapa North": ["Ayete", "Tapa", "Igbo Ora"],
  "Ido": ["Ido Town", "Omi Adio", "Apata", "Akufo", "Bakatari"],
  "Irepo": ["Kisi", "Igbeti"],
  "Iseyin": ["Iseyin Town", "Sagbo", "Ipo", "Koso"],
  "Itesiwaju": ["Otu", "Okaka", "Baba Ode", "Igbojaiye"],
  "Iwajowa": ["Iwere-Ile", "Iganna", "Iwere"],
  "Kajola": ["Okeho", "Ilero", "Isemi Ile", "Ilua"],
  "Lagelu": ["Lalupon", "Lagun", "Monatan", "Akobo Ojurin"],
  "Ogbomosho North": ["Ogbomosho", "Arowomole", "Masifa", "Sabo", "Takie"],
  "Ogbomosho South": ["Arowomole", "Akata", "Ijeru", "Oke-Ado"],
  "Ogo Oluwa": ["Ajaawa", "Odo Oba", "Lagbedu"],
  "Olorunsogo": ["Igbeti", "Ikoloba"],
  "Oluyole": ["Idi Ayunre", "Podo", "New Garage", "Olorunsogo", "Abayomi", "Alomaja"],
  "Ona Ara": ["Akanran", "Olunloyo", "Gbaremu", "Amuloko", "Olorunda"],
  "Orelope": ["Igboho", "Igbope", "Alaguntan"],
  "Ori Ire": ["Ikoyi-Ile", "Tede Area"],
  "Oyo": ["Oyo Town", "Durbar", "Fiditi Area"],
  "Oyo East": ["Agbongbon", "Akesan", "Oke Apo"],
  "Saki East": ["Ago-Amodu", "Oje Owode", "Sepeteri"],
  "Saki West": ["Saki Town", "Asabari", "Ogbooro"],
  "Surulere": ["Iresa Adu", "Iresa Apa", "Oko"],

  // --- ABIA ---
  "Aba North": ["Ogbor Hill", "Uratta", "Eziama", "Ariaria", "Umuola"],
  "Aba South": ["Aba Main", "Asa Road", "Ngwa Road", "Cemetery Road", "Omuma Road"],
  "Arochukwu": ["Arochukwu Town", "Ohafia-Arochukwu Road", "Atani", "Iheosu"],
  "Bende": ["Bende Town", "Igbere", "Ozuitem", "Ugwueke", "Alayi"],
  "Ikwuano": ["Oboro", "Ibere", "Ariam", "Oloko"],
  "Isiala Ngwa North": ["Okpuala Ngwa", "Amapu Ntigha"],
  "Isiala Ngwa South": ["Omoba", "Mbutu", "Ovu Ngwa"],
  "Isuikwuato": ["Mbalano", "Ovim", "Achara", "Ezere"],
  "Obi Ngwa": ["Mgboko", "Abayi", "Onuma"],
  "Ohafia": ["Ohafia Town", "Akanu", "Abiriba", "Nkporo"],
  "Osisioma": ["Osisioma Junction", "Aba-Owerri Road", "Umuojima"],
  "Ugwunagbo": ["Ugwunagbo Town", "Obuzor", "Ihie"],
  "Ukwa East": ["Akwete", "Azza", "Obohia"],
  "Ukwa West": ["Oke Ikpe", "Asa North", "Obokwe"],
  "Umuahia North": ["Umuahia Town", "Ibeku", "Ohokobe", "World Bank", "Amaoba"],
  "Umuahia South": ["Apumiri", "Ubakala", "Ohiya", "Nsirimo"],
  "Umunneochi": ["Nkwoagu", "Lekwesi", "Mbala", "Umuchieze"],

  // --- ADAMAWA ---
  "Demsa": ["Demsa Town", "Borrong", "Dilli"],
  "Fufore": ["Fufore Town", "Malabu", "Wuro Bokki"],
  "Ganye": ["Ganye Town", "Sangassumi", "Gurumpawo"],
  "Girei": ["Girei Town", "Vinikilang", "Gereng"],
  "Gombi": ["Gombi Town", "Tawa", "Boga"],
  "Guyuk": ["Guyuk Town", "Banjiram", "Chikila"],
  "Hong": ["Hong Town", "Pella", "Hildi", "Gaya"],
  "Jada": ["Jada Town", "Mbulo", "Kojoli"],
  "Lamurde": ["Lamurde Town", "Gyawana", "Suwa"],
  "Madagali": ["Madagali Town", "Gulak", "Hyambula"],
  "Maiha": ["Maiha Town", "Belel", "Sorau"],
  "Mayo Belwa": ["Mayo Belwa Town", "Binyeri", "Ndikong"],
  "Michika": ["Michika Town", "Bazza", "Futuless"],
  "Mubi North": ["Mubi Town", "Lokuwa", "Barama"],
  "Mubi South": ["Mubi South Town", "Gude", "Mujara"],
  "Numan": ["Numan Town", "Imburu", "Bare"],
  "Shelleng": ["Shelleng Town", "Kiri", "Bodwai"],
  "Song": ["Song Town", "Dumne", "Kilange", "Zumo"],
  "Toungo": ["Toungo Town", "Gumti", "Dawo"],
  "Yola North": ["Jimeta", "Doubeli", "Alkalawa", "Luggere"],
  "Yola South": ["Yola Town", "Ngurore", "Mbamba", "Namtari"],

  // --- AKWA IBOM ---
  "Abak": ["Abak Town", "Afaha Obong", "Midim"],
  "Eastern Obolo": ["Okoroete", "Okorombokho"],
  "Eket": ["Eket Town", "Afaha Atai", "Idua", "Okon"],
  "Esit Eket": ["Uquo", "Etebi"],
  "Essien Udim": ["Afaha Ikot Ebak", "Okon", "Adiasim"],
  "Etim Ekpo": ["Utu Etim Ekpo", "Iwukem", "Obong Ntak"],
  "Etinan": ["Etinan Town", "Ikot Isong", "Mbioto"],
  "Ibeno": ["Ibeno Town", "Mkpanak", "Iwuo-Okpo"],
  "Ibesikpo Asutan": ["Nung Udoe", "Ikot Atang", "Oku"],
  "Ibiono-Ibom": ["Oko Ita", "Use Abat", "Ididep"],
  "Ika": ["Ikot Ibritam", "Achan Ika", "Ika Annang"],
  "Ikono": ["Ibiaku Ntok Okpo", "Nung Ukim", "Ukpom"],
  "Ikot Abasi": ["Ikot Abasi Town", "Ikot Okoro", "Edemaya"],
  "Ikot Ekpene": ["Ikot Ekpene Town", "Uruk Uso", "Ifuho"],
  "Ini": ["Odoro Ikpe", "Ikpe Ikot Nkon", "Mbiabong"],
  "Itu": ["Itu Town", "Mbak Atai", "Oku Iboku", "Ayadehe"],
  "Mbo": ["Enwang", "Ibaka", "Effiat", "Uda"],
  "Mkpat-Enin": ["Mkpat Enin Town", "Ikot Akpaden", "Ikot Obio Nso"],
  "Nsit-Atai": ["Odot", "Ikot Akpabio"],
  "Nsit-Ibom": ["Afaha Offiong", "Obo Atai", "Ikot Nseyen"],
  "Nsit-Ubium": ["Ikot Edibon", "Eket Road", "Ubium"],
  "Obot Akara": ["Nto Edino", "Ikot Abia Osom"],
  "Okobo": ["Okopedi", "Amadum", "Atabong"],
  "Onna": ["Abat", "Awa Iman", "Oniong", "Nung Ndem"],
  "Oron": ["Oron Town", "Esin Ufot", "Okpo"],
  "Oruk Anam": ["Ikot Ibritam", "Inen", "Nung Ikot"],
  "Ukanafun": ["Ikot Akpa Nkuk", "Nkek", "Afaha Obo"],
  "Udung-Uko": ["Eyofin", "Udung Adatang"],
  "Uruan": ["Idu", "Anakpa", "Mbiaya"],
  "Urue-Offong/Oruko": ["Urue Offong", "Oyoku", "Uboro Oro"],
  "Uyo": ["Uyo Town", "Ewet Housing", "Osongama", "Shelter Afrique", "Nsikak Eduok", "Abak Road", "Nwaniba", "Itam"],

  // --- ANAMBRA ---
  "Aguata": ["Ekwulobia", "Isuofia", "Uga", "Umuchu", "Igboukwu"],
  "Anambra East": ["Otuocha", "Nando", "Igbariam", "Umuoba Anam"],
  "Anambra West": ["Nzam", "Umuenwelum", "Oroma-Etiti", "Mmiata"],
  "Anaocha": ["Neni", "Adazi-Nnukwu", "Nri", "Agulu", "Ichida"],
  "Awka North": ["Achalla", "Ugbenu", "Mgbakwu", "Isu Aniocha"],
  "Awka South": ["Awka Town", "Amawbia", "Nibo", "Okpuno", "Ifite Awka", "Aroma", "Udoka Estate"],
  "Ayamelum": ["Anaku", "Omor", "Umumbo", "Umueje", "Igbakwu"],
  "Dunukofia": ["Ukpo", "Ukwulu", "Ifitedunu", "Umunnachi", "Nawgu"],
  "Ekwusigo": ["Ozubulu", "Ichi", "Ihembosi", "Oraifite"],
  "Idemili North": ["Ogidi", "Obosi", "Umuoji", "Nkpor", "Uke", "Abatete"],
  "Idemili South": ["Ojoto", "Nnobi", "Alor", "Akwa Ukwu", "Nokwa"],
  "Ihiala": ["Ihiala Town", "Okija", "Uli", "Amorka", "Lilu", "Mbosi"],
  "Njikoka": ["Abagana", "Enugwu-Ukwu", "Nimo", "Nawfia", "Abba"],
  "Nnewi North": ["Nnewi Town", "Uruagu", "Umudim", "Otolo", "Nnewichi"],
  "Nnewi South": ["Ukpor", "Amichi", "Ezinifite", "Osumenyi", "Ebenator"],
  "Ogbaru": ["Atani", "Ogbakuba", "Ochuche", "Okpoko"],
  "Onitsha North": ["Onitsha Main", "Inland Town", "GRA Onitsha", "American Quarters"],
  "Onitsha South": ["Fegge", "Woliwo", "Odoakpu", "Main Market", "Bridge Head"],
  "Orumba North": ["Ajalli", "Ndiowu", "Ndiokpalaeze", "Amaokpala", "Awgbu"],
  "Orumba South": ["Umunze", "Ezira", "Akpu", "Ihite", "Ogbunka"],
  "Oyi": ["Nteje", "Awkuzu", "Ogbunike", "Umunya", "Umudioka"],

  // --- BAUCHI ---
  "Alkaleri": ["Alkaleri Town", "Futuk", "Gwaram", "Pali"],
  "Bauchi": ["Bauchi Town", "Birshi", "Dandango", "GRA Bauchi", "Wuntin Dada", "Yelwa"],
  "Bogoro": ["Bogoro Town", "Boi", "Bar", "Lusa"],
  "Damban": ["Damban Town", "Jalam", "Gargawa"],
  "Darazo": ["Darazo Town", "Gabarin", "Sade", "Lago"],
  "Dass": ["Dass Town", "Baraya", "Wandi", "Bundot"],
  "Gamawa": ["Gamawa Town", "Udubo", "Kafin Romi", "Gololo"],
  "Ganjuwa": ["Kafin Madaki", "Nasarawa", "Yali", "Miya"],
  "Giade": ["Giade Town", "Isawa", "Zirami", "Uzum"],
  "Itas/Gadau": ["Itas", "Gadau", "Buzawa", "Mashema"],
  "Jama'are": ["Jama'are Town", "Jurara", "Dogon Jeji"],
  "Katagum": ["Azare", "Bidir", "Gama", "Chinade"],
  "Kirfi": ["Kirfi Town", "Cheledi", "Wanka", "Badara"],
  "Misau": ["Misau Town", "Hardawa", "Zadawa", "Akuyam"],
  "Ningi": ["Ningi Town", "Burra", "Balma", "Tiffi"],
  "Shira": ["Yana", "Beli", "Disina", "Bukul"],
  "Tafawa Balewa": ["Tafawa Balewa Town", "Bununu", "Dajin", "Lere"],
  "Toro": ["Toro Town", "Jama'a", "Lame", "Tilden Fulani", "Ribina"],
  "Warji": ["Katangan Warji", "Tiyin", "Gudun"],
  "Zaki": ["Katagum", "Zaki Town", "Tashena", "Sakwa"],

  // --- BAYELSA ---
  "Brass": ["Twon Brass", "Okpoama", "Ewoama", "Beletiama"],
  "Ekeremor": ["Ekeremor Town", "Peretorugbene", "Oporoma Road"],
  "Kolokuma/Opokuma": ["Kaiama", "Opokuma", "Sampou", "Odi"],
  "Nembe": ["Nembe Town", "Bassambiri", "Ogbolomabiri", "Okoroma"],
  "Ogbia": ["Ogbia Town", "Oloibiri", "Otuasega", "Kolo", "Emeyal"],
  "Sagbama": ["Sagbama Town", "Toru-Orua", "Bolou-Orua", "Tungbo"],
  "Southern Ijaw": ["Oporoma", "Amassoma", "Agbura", "Peremabiri"],
  "Yenagoa": ["Yenagoa Town", "Swali", "Biogbolo", "Kpansia", "Agudama", "Akenfa", "Okaka", "Edepie"],

  // --- BENUE ---
  "Ado": ["Igumale", "Ulayi", "Agila", "Rijo"],
  "Agatu": ["Obagaji", "Ogbaulu", "Okokolo"],
  "Apa": ["Ugbokpo", "Oiji", "Ojope"],
  "Buruku": ["Buruku Town", "Mbaakura", "Mbarkum", "Shorov"],
  "Gboko": ["Gboko Town", "Yandev", "Mbadam", "Igyarev", "Mbakper"],
  "Guma": ["Gbajimba", "Uikpiam", "Daudu", "Agasha"],
  "Gwer East": ["Aliade", "Mbalom", "Ikyonov", "Ugee"],
  "Gwer West": ["Naka", "Sengev", "Tijime", "Avihijime"],
  "Katsina-Ala": ["Katsina-Ala Town", "Abaji", "Mbayongo", "Yooyo"],
  "Konshisha": ["Tse-Agberagba", "Mbaakpur", "Mbayegh"],
  "Kwande": ["Adikpo", "Anwase", "Jato-Aka", "Adagi"],
  "Logo": ["Ugba", "Mbadyul", "Turan", "Yonov"],
  "Makurdi": ["Makurdi Town", "Wurukum", "High Level", "Wadata", "North Bank", "Adeke", "Ter Guma"],
  "Obi": ["Obi Town", "Adum East", "Okwutungbe"],
  "Ogbadibo": ["Otupko", "Otukpa", "Orokam", "Owukpa"],
  "Ohimini": ["Idekpa", "Awume", "Onyagede"],
  "Oju": ["Oju Town", "Ojo", "Oboru", "Ibilla"],
  "Okpokwu": ["Okpoga", "Ichama", "Ojigo", "Edumoga"],
  "Otukpo": ["Otukpo Town", "Adoka", "Upu", "Otobi", "Asa"],
  "Tarka": ["Wannune", "Mbaayo", "Mbachoughul"],
  "Ukum": ["Zaki Biam", "Aterayange", "Borikyo", "Kendev"],
  "Ushongo": ["Lessel", "Mbagwaza", "Mbagba", "Utange"],
  "Vandeikya": ["Vandeikya Town", "Mbagbam", "Tsambe", "Mbaduku"],

  // --- BORNO ---
  "Abadam": ["Malum Fatori", "Arege"],
  "Askira/Uba": ["Askira", "Uba", "Lassa", "Huyum"],
  "Bama": ["Bama Town", "Banki", "Dar El Jamal"],
  "Bayo": ["Biryel", "Gamadadi", "Jara Dali"],
  "Biu": ["Biu Town", "Mandaragirau", "Buratai", "Miringa"],
  "Chibok": ["Chibok Town", "Garu", "Whuntaku"],
  "Damboa": ["Damboa Town", "Azur", "Mulgwai", "Kafa"],
  "Dikwa": ["Dikwa Town", "Gajibo", "Mudu"],
  "Gubio": ["Gubio Town", "Ardowa", "Kingowa"],
  "Guzamala": ["Gudumbali", "Amanwa"],
  "Gwoza": ["Gwoza Town", "Pulka", "Kirawa", "Limankara"],
  "Hawul": ["Azare", "Kwajaffa", "Shafa", "Marama"],
  "Jere": ["Khaddamari", "Dusuman", "Gongulong", "Maimusari", "Custom Area"],
  "Kaga": ["Benishiekh", "Galangi", "Ngamdu"],
  "Kala/Balge": ["Rann", "Jilbe", "Kala"],
  "Konduga": ["Konduga Town", "Auno", "Maimakari", "Kawuri"],
  "Kukawa": ["Kukawa Town", "Baga", "Cross Kauwa"],
  "Kwaya Kusar": ["Kwaya Kusar Town", "Guwar", "Wawa"],
  "Mafa": ["Mafa Town", "Anadua", "Gajibo"],
  "Magumeri": ["Magumeri Town", "Hoyo", "Gajiganna"],
  "Maiduguri": ["Maiduguri Town", "Bulumkutu", "Gwange", "Bolori", "Shehuri", "GRAs", "Pompomari"],
  "Marte": ["Marte Town", "Kirenuwa", "Kirenowa"],
  "Mobbar": ["Damasak", "Zari", "Gashagar"],
  "Monguno": ["Monguno Town", "Kumaganam", "Damakuli"],
  "Ngala": ["Ngala Town", "Gamboru", "Wulgo", "Logumani"],
  "Nganzai": ["Gajiram", "Damaram", "Sugun"],
  "Shani": ["Shani Town", "Kubo", "Bargu"],

  // --- CROSS RIVER ---
  "Abi": ["Itigidi", "Ebom", "Imabana", "Ekureku"],
  "Akamkpa": ["Akamkpa Town", "Uyanga", "Aking", "Ojor"],
  "Akpabuyo": ["Ikang", "Atimbo", "Idundu"],
  "Bakassi": ["Ikang", "Abana", "Archibong"],
  "Bekwarra": ["Abuochiche", "Iyala", "Nyanya", "Gakem"],
  "Biase": ["Akpet Central", "Adim", "Umon", "Ojor"],
  "Boki": ["Boje", "Bateriko", "Bendem", "Buda", "Okundi"],
  "Calabar Municipal": ["Calabar Town", "Anantigha", "Ikot Ansa", "Ediba", "Akai Effa", "Goldie"],
  "Calabar South": ["Anantigha", "Henshaw Town", "Jebs", "Akim"],
  "Etung": ["Effraya", "Etomi", "Bendeghe Ekiem"],
  "Ikom": ["Ikom Town", "Alesi", "Ajasor", "Olulumo"],
  "Obanliku": ["Sankwala", "Bisu", "Bebi", "Busi"],
  "Obubra": ["Apiapum", "Obubra Town", "Ofodua", "Ovonum", "Ofumbongha"],
  "Obudu": ["Obudu Town", "Begiaba", "Begiading", "Ukpe"],
  "Odukpani": ["Odukpani Town", "Adiabo", "Akamkpa Road", "Okurikang"],
  "Ogoja": ["Ogoja Town", "Ishibori", "Ekajuk", "Mbube"],
  "Yakuur": ["Ugep", "Mkpani", "Idomi", "Ekori"],
  "Yala": ["Okpoma", "Ogoja-Yala Road", "Ijiraga", "Ebo", "Okuku"],

  // --- DELTA ---
  "Aniocha North": ["Issele-Uku", "Issele-Mkpitime", "Onicha-Ugbo", "Obomkpa", "Idumuje-Ugboko"],
  "Aniocha South": ["Ogwashi-Uku", "Nsukwa", "Ejeme", "Ubulu-Unor", "Ubulu-Uku"],
  "Bomadi": ["Bomadi Town", "Kpakiama", "Akugbene"],
  "Burutu": ["Burutu Town", "Ogulagha", "Obotebe", "Forcados"],
  "Ethiope East": ["Isiokolo", "Ovu", "Kokori", "Okpara", "Eku"],
  "Ethiope West": ["Oghara", "Mosogar", "Jesse", "Ogharefe", "Ugbenu"],
  "Ika North East": ["Owa-Oyibu", "Ute-Okpu", "Ute-Ogbeje", "Idumuesah"],
  "Ika South": ["Agbor", "Boji-Boji", "Ozanogogo", "Abavo", "Alifekede"],
  "Isoko North": ["Ozoro", "Owhelogbo", "Ellu", "Ofagbe", "Ovrode"],
  "Isoko South": ["Oleh", "Uzere", "Aviara", "Olomoro", "Enwhe"],
  "Ndokwa East": ["Aboh", "Ase", "Ibrede", "Akarai", "Ossissa"],
  "Ndokwa West": ["Kwale", "Ogwashi-Uku Road", "Utagba Ogbe", "Emu", "Ogume"],
  "Okpe": ["Orerokpe", "Adeje", "Osubi", "Oha", "Mereje"],
  "Oshimili North": ["Akuku", "Ibusa", "Okpanam", "Illah", "Ukala"],
  "Oshimili South": ["Asaba", "Cable Point", "Okwe", "Oko", "GRA Asaba", "Nnebisi Road"],
  "Patani": ["Patani Town", "Abare", "Toru-Angiama"],
  "Sapele": ["Sapele Town", "Amukpe", "Elume", "Ogorode", "Okirighwre"],
  "Udu": ["Otor-Udu", "Aladja", "Orhuwhorun", "Ovwian", "Ekete"],
  "Ughelli North": ["Ughelli Town", "Ogor", "Orogun", "Agadama", "Evwreni"],
  "Ughelli South": ["Otu-Jeremi", "Ewu", "Egbo", "Ekakpamre", "Olomu"],
  "Ukwuani": ["Obiaruku", "Umutu", "Ebedei", "Umukwata", "Amai"],
  "Uvwie": ["Effurun", "Ekpan", "Ugborikoko", "Okuokoko", "Enerhen", "PTI Road", "Jakpa"],
  "Warri North": ["Koko", "Opuama", "Sapele Road Warri"],
  "Warri South": ["Warri Town", "Edjeba", "Okumagba Avenue", "Airport Road", "Ajamimogha", "Pessu", "Igbudu"],
  "Warri South West": ["Ogbe-Ijoh", "Oporoza", "Okerenkoko", "Oporoza Road"],

  // --- EBONYI ---
  "Abakaliki": ["Abakaliki Town", "Nkaliki", "Azugwu", "Akwuda", "Ede-Ebonyi"],
  "Afikpo North": ["Afikpo Town", "Amaozara", "Ozizza", "Ohaisu", "Itim"],
  "Afikpo South": ["Nguzu Edda", "Owutu Edda", "Amangwu Edda"],
  "Ebonyi": ["Ugbodo", "Mbeke", "Ndiabor", "Nkaleke"],
  "Ezza North": ["Ebiaji", "Nkomoro", "Ogboji"],
  "Ezza South": ["Onueke", "Echara", "Imeabali", "Amuzu"],
  "Ikwo": ["Noyo Alike", "Echialike", "Ekpelu", "Ndufu Alike"],
  "Ishielu": ["Ezillo", "Nkalaha", "Ohozara", "Agba"],
  "Ivo": ["Isiaka", "Akaeze", "Ishiagu", "Ngwogwo"],
  "Izzi": ["Iboko", "Ishieke", "Igbeagu", "Ebya", "Mgbabeluzor"],
  "Ohaozara": ["Obiozara", "Ugbom", "Okposi", "Ugwu Langwu", "Umunaga"],
  "Ohaukwu": ["Ezzamgbo", "Ngbo", "Umugadu", "Okposhi"],
  "Onicha": ["Isu", "Abaomege", "Oshiri", "Ukawu"],

  // --- EDO ---
  "Akoko-Edo": ["Igarra", "Ibillo", "Ososo", "Enwan", "Makamagbe"],
  "Egor": ["Uselu", "Uwelu", "Okhoro", "Useh", "Egor Town", "Evbareke"],
  "Esan Central": ["Irrua", "Ewu", "Opoji", "Ugbegun"],
  "Esan North-East": ["Uromi", "Egbele", "Arue", "Uzea"],
  "Esan South-East": ["Ubiaja", "Ohordua", "Ujogba", "Ewoyi"],
  "Esan West": ["Ekpoma", "Ukhun", "Ogwa", "Emaudo"],
  "Etsako Central": ["Fugar", "Ogbona", "Ekperi", "Iviukwe"],
  "Etsako East": ["Agenebode", "Okpella", "Weppa", "Imiegba"],
  "Etsako West": ["Auchi", "Jattu", "Uzairue", "Iyakpi", "South Ibie"],
  "Igueben": ["Igueben Town", "Ebelle", "Amahor", "Udo"],
  "Ikpoba Okha": ["Idogbo", "Obayantor", "Ologbo", "Ironsa", "Oregbeni", "Ugbekun"],
  "Orhionmwon": ["Abudu", "Ugboko", "Aibiokula", "Iyoba"],
  "Oredo": ["Benin City", "GRA Benin", "New Benin", "Ogida", "Ibiwe", "Ekenwan", "Sakponba Road", "Etete"],
  "Ovia North-East": ["Okada", "Ofosu", "Uhen", "Isiuwa", "Oluku", "Ekiadolor"],
  "Ovia South-West": ["Iguobazuwa", "Udo", "Siluko", "Ofunama"],
  "Owan East": ["Afuze", "Emai", "Otuo", "Igue", "Uokha"],
  "Owan West": ["Sabongida-Ora", "Sobe", "Ozalla", "Uhonmora"],
  "Uhunmwonde": ["Ehor", "Irhue", "Ugonoba", "Isi"],

  // --- EKITI ---
  "Ado Ekiti": ["Ado Ekiti Town", "Ijigbo", "Oke Ila", "Odo Ado", "Irona", "Ajilosun", "Adebayo", "Basiri"],
  "Efon": ["Efon Alaaye", "Oba-Ile"],
  "Ekiti East": ["Omuo Ekiti", "Isinbode", "Kota Ekiti", "Iro Ayeteju"],
  "Ekiti South-West": ["Ilawe Ekiti", "Ogotun Ekiti", "Igbara Odo"],
  "Ekiti West": ["Aramoko Ekiti", "Erijiyan", "Okemesi", "Ikogosi"],
  "Emure": ["Emure Ekiti", "Eporo"],
  "Gbonyin": ["Ode Ekiti", "Aisegba", "Agbado Ekiti", "Imesi Ekiti"],
  "Ido Osi": ["Ido Ekiti", "Usi Ekiti", "Ifaki Ekiti", "Orin Ekiti", "Ilogbo Ekiti"],
  "Ijero": ["Ijero Ekiti", "Ikoro Ekiti", "Ipoti Ekiti", "Ijurin Ekiti"],
  "Ikere": ["Ikere Ekiti", "Ugele", "Oke Osun"],
  "Ikole": ["Ikole Ekiti", "Odo Ayedun", "Isaba", "Ipao"],
  "Ilejemeje": ["Iye Ekiti", "Iludun Ekiti", "Ijesa Isu"],
  "Irepodun/Ifelodun": ["Igede Ekiti", "Iyin Ekiti", "Igbemo Ekiti", "Awo Ekiti"],
  "Ise/Orun": ["Ise Ekiti", "Orun Ekiti", "Afolu", "Ijan Ekiti"],
  "Moba": ["Otun Ekiti", "Igogo Ekiti", "Osan Ekiti", "Osun Ekiti"],
  "Oye": ["Oye Ekiti", "Ayegbaju", "Isan Ekiti", "Ilupeju Ekiti", "Itapa Ekiti"],

  // --- ENUGU ---
  "Aninri": ["Ndeaboh", "Nenwe", "Mpu", "Okpanku", "Oduma"],
  "Awgu": ["Awgu Town", "Mgbowo", "Mgbidi", "Mmaku", "Obeagu", "Agbogugu"],
  "Enugu East": ["Abakpa Nike", "Trans Ekulu Extension", "Emene", "Amechi", "Nike"],
  "Enugu North": ["GRA Enugu", "Independence Layout", "Trans Ekulu", "Ogui", "New Haven", "Coal Camp", "Asata", "Ogbete"],
  "Enugu South": ["Uwani", "Agbani Road", "Maryland", "Akwuke", "Amechi", "Obeagu Uno"],
  "Ezeagu": ["Aguobu Owa", "Iwollo", "Aguobu Umumba", "Olo"],
  "Igbo Etiti": ["Ogbede", "Diogbe", "Ekwegbe", "Ozalla", "Ukehe"],
  "Igbo Eze North": ["Enugu Ezike", "Uda", "Umuopu", "Essodo"],
  "Igbo Eze South": ["Ibagwa-Aka", "Iheaka", "Itchi", "Unadu"],
  "Isi Uzo": ["Ikem", "Eha Amufu", "Mbu", "Neke"],
  "Nkanu East": ["Amagunze", "Nara", "Nkerefi", "Mburumbu", "Ugbawka"],
  "Nkanu West": ["Agbani", "Ozalla", "Akegbe Ugwu", "Akpugo", "Amodu"],
  "Nsukka": ["Nsukka Town", "Ede-Oballa", "Opi", "Obimo", "Lejja", "Okpuje", "GRA Nsukka"],
  "Oji River": ["Oji River Town", "Achi", "Awlaw", "Inyi", "Ugwuoba"],
  "Udenu": ["Obollo Afor", "Obollo Eke", "Orba", "Imilike", "Ezimo"],
  "Udi": ["Udi Town", "Ngwo", "9th Mile", "Nachi", "Abia", "Awhum"],
  "Uzo Uwani": ["Umulokpa", "Adaba", "Adani", "Opanda", "Nimbo"],

  // --- GOMBE ---
  "Akko": ["Kumo", "Pindiga", "Tumu", "Kalshingi"],
  "Balanga": ["Bambam", "Swa", "Talasse", "Gelengu"],
  "Billiri": ["Billiri Town", "Bare", "Todi", "Tangle"],
  "Dukku": ["Dukku Town", "Malala", "Waziri North", "Jamari"],
  "Funakaye": ["Bajoga", "Ashaka", "Jillahi", "Tongo"],
  "Gombe": ["Gombe Town", "Bolari", "Pantami", "GRA Gombe", "Tudun Wada", "Herwagana"],
  "Kaltungo": ["Kaltungo Town", "Awak", "Kamo", "Ture"],
  "Kwami": ["Mallam Sidi", "Kwami Town", "Doho", "Bojude"],
  "Nafada": ["Nafada Town", "Jigawa", "Birin Fulani"],
  "Shongom": ["Boh", "Filiya", "Gwandum", "Kushi"],
  "Yamaltu/Deba": ["Deba", "Hinna", "Kuri", "Lubona", "Gwani"],

  // --- IMO ---
  "Aboh Mbaise": ["Aboh", "Nguru", "Umuokirika", "Mbutu"],
  "Ahiazu Mbaise": ["Afor Oru", "Mpam", "Ogbe", "Oparanadim"],
  "Ehime Mbano": ["Umuezeala", "Umueze", "Nsu", "Agbaja", "Umualumaku"],
  "Ezinihitte": ["Itu", "Amumara", "Eziudo", "Onicha", "Oboama"],
  "Ideato North": ["Urualla", "Obodoukwu", "Akokwa", "Isiekenesi", "Uzii"],
  "Ideato South": ["Dikenafai", "Umuchima", "Umuma Isiaku", "Amanator"],
  "Ihitte/Uboma": ["Isinweke", "Abueke", "Amakohia", "Umuihi"],
  "Ikeduru": ["Iho", "Ngugo", "Inyishi", "Amaimo", "Avuvu"],
  "Isiala Mbano": ["Umuelemai", "Amauzari", "Osuh", "Ugiri", "Osu Owerre"],
  "Isu": ["Isu Njaba", "Amandugba", "Amurie Omanze", "Ekwe", "Umuaka"],
  "Mbaitoli": ["Nworieubi", "Afara", "Ogbaku", "Eziama", "Ogbaku"],
  "Ngor Okpala": ["Umuneke", "Ngor", "Eziama", "Imerienwe", "Umuohii"],
  "Njaba": ["Atta", "Umuaka", "Okwudor", "Amucha"],
  "Nkwerre": ["Nkwerre Town", "Owerre Nkwoji", "Amaokpara", "Umudi"],
  "Nwangele": ["Abba", "Abajah", "Kara", "Dim Na Nume"],
  "Obowo": ["Otoko", "Avutu", "Alike", "Umunachi"],
  "Oguta": ["Oguta Town", "Egwe", "Orsu Obodo", "Mgbelle", "Nnebukwu"],
  "Ohaji/Egbema": ["Ohaji", "Egbema", "Mgbirichi", "Mmahu", "Umuagwo"],
  "Okigwe": ["Okigwe Town", "Ihube", "Aku", "Umulolo", "Otan-Chara"],
  "Orlu": ["Orlu Town", "Mgbee", "Ihioma", "Amaifeke", "Umuna"],
  "Orsu": ["Orsu Town", "Awo-Idemili", "Amaruru", "Ebenato", "Assa"],
  "Oru East": ["Omuma", "Akatta", "Amagu", "Amiri", "Ofekata"],
  "Oru West": ["Mgbidi", "Ibiassu", "Aji", "Ozara", "Nempi"],
  "Owerri Municipal": ["Owerri Town", "Ikenegbu", "Aladinma", "GRA Owerri", "New Owerri", "Ikenegbu Extension"],
  "Owerri North": ["Orji", "Emekuku", "Egbu", "Uratta", "Obibiezena", "Ihitaoha"],
  "Owerri West": ["Umuguma", "Nekede", "Ihiagwa", "Obinze", "Avu", "Eziobodo", "Oforola"],
  "Onuimo": ["Okwe", "Okwele", "Umuna", "Ezelu"],

  // --- JIGAWA ---
  "Auyo": ["Auyo Town", "Ayan", "Gamafoi", "Gatafa"],
  "Babura": ["Babura Town", "Kanya", "Batali", "Kyamba"],
  "Biriniwa": ["Biriniwa Town", "Kazura", "Matarara", "Dangwaleri"],
  "Birnin Kudu": ["Birnin Kudu Town", "Kangire", "Kantoga", "Sundumina"],
  "Buji": ["Gantsa", "Buji Town", "Gantsa"],
  "Dutse": ["Dutse Town", "Limawa", "Kiyawa Road", "Madobi", "Sakwaya"],
  "Gagarawa": ["Gagarawa Town", "Madaka", "Medu"],
  "Garki": ["Garki Town", "Budura", "Kore", "Muku"],
  "Gumel": ["Gumel Town", "Hammado", "Baikarya", "Zango"],
  "Guri": ["Guri Town", "Adiyani", "Dawa", "Lafiya"],
  "Gwaram": ["Gwaram Town", "Basirka", "Fagam", "Maruta"],
  "Gwiwa": ["Gwiwa Town", "Buntusu", "Danzomo", "Guntai"],
  "Hadejia": ["Hadejia Town", "Matsaro", "Atafi", "Kasuwar Kuda"],
  "Jahun": ["Jahun Town", "Gunka", "Harbo Sabuwa", "Aujara"],
  "Kafin Hausa": ["Kafin Hausa Town", "Jabo", "Mezan", "Ruba"],
  "Kaugama": ["Kaugama Town", "Jarkosa", "Dabuwaran", "Askandu"],
  "Kazaure": ["Kazaure Town", "Ba'auzini", "Gada", "Kanti"],
  "Kiri Kasama": ["Kiri Kasama Town", "Marma", "Baturiya"],
  "Kiyawa": ["Kiyawa Town", "Andaza", "Kwanda", "Shuwarin"],
  "Maigatari": ["Maigatari Town", "Galadi", "Balarabe", "Madara"],
  "Malam Madori": ["Malam Madori Town", "Arki", "Garun Gabas", "Tashena"],
  "Miga": ["Miga Town", "Sabuwa", "Hantsu", "Koya"],
  "Ringim": ["Ringim Town", "Dabi", "Chai Chai", "Sankara"],
  "Roni": ["Roni Town", "Baragumi", "Dansure", "Kwaita"],
  "Sule Tankarkar": ["Sule Tankarkar Town", "Dangwada", "Jeke", "Shabaru"],
  "Taura": ["Taura Town", "Chukuto", "Majia", "Kiri"],
  "Yankwashi": ["Yankwashi Town", "Zungumba", "Gwarta", "Karkarna"],

  // --- KADUNA ---
  "Birnin Gwari": ["Birnin Gwari Town", "Kuyelo", "Maganda", "Dogon Dawa"],
  "Chikun": ["Kujama", "Chikun Town", "Sabon Tasha", "Narayi", "Gonin Gora", "Kakau", "Barnawa", "Kakuri"],
  "Giwa": ["Giwa Town", "Shika", "Yakawada", "Kudai"],
  "Igabi": ["Igabi Town", "Rigachikun", "Rigasa", "Afaka", "Kwarau", "Birnin Yero", "Jaji"],
  "Ikara": ["Ikara Town", "Pala", "Kurmin Kogi", "Saya Saya"],
  "Jaba": ["Kwoi", "Nok", "Dura Bitaro", "Samban"],
  "Jema'a": ["Kafanchan", "Kagoma", "Godogodo", "Maigizo", "Jagindi Tasha"],
  "Kachia": ["Kachia Town", "Katari", "Agunu", "Kwasam", "Awon"],
  "Kaduna North": ["Kaduna Town", "Ungwan Rimi", "Ungwan Dosa", "Kabala Costain", "Kawo", "Ungwan Shanu", "Badarawa"],
  "Kaduna South": ["Makera", "Tudun Wada", "Kakuri", "Barnawa", "Sabon Gari Kaduna", "Ungwan Muazu"],
  "Kagarko": ["Kagarko Town", "Jere", "Kuse", "Kukui"],
  "Kajuru": ["Kajuru Town", "Kufana", "Afogo", "Kallah"],
  "Kaura": ["Kaura Town", "Manchok", "Bondong", "Fada"],
  "Kauru": ["Kauru Town", "Dawaki", "Badurum", "Kwassam"],
  "Kubau": ["Kubau Town", "Dutsen Wai", "Anchau", "Kargi"],
  "Kudan": ["Hunkuyi", "Kudan Town", "Likoro", "Zabi"],
  "Lere": ["Saminaka", "Lere Town", "Kayarda", "Gure", "Ramindop"],
  "Makarfi": ["Makarfi Town", "Gazara", "Danguzuri", "Meyere"],
  "Sabon Gari": ["Sabon Gari Zaria", "Bomo", "Jushi", "Chikaji", "Palladan"],
  "Sanga": ["Gwantu", "Abuja Sanga", "Arak", "Nandu", "Fadan Karshi"],
  "Soba": ["Maigana", "Soba Town", "Gimba", "Turawa"],
  "Zangon Kataf": ["Zonkwa", "Zangon Kataf Town", "Kamanton", "Madakiya", "Kafanchan Road"],
  "Zaria": ["Zaria City", "Samaru", "Gyallesu", "Tudun Wada Zaria", "Kwangila", "Palladan", "Kufena", "Dakace"],

  // --- KANO ---
  "Ajingi": ["Ajingi Town", "Gafasa", "Balare", "Dabin Kanawa"],
  "Albasu": ["Albasu Town", "Faragai", "Gagarame", "Tsangaya"],
  "Bagwai": ["Bagwai Town", "Gadanya", "Rimi", "Kiyawa"],
  "Bebeji": ["Bebeji Town", "Anadariya", "Baguda", "Gwarmai"],
  "Bichi": ["Bichi Town", "Badayawa", "Kaukau", "Kakabo"],
  "Bunkure": ["Bunkure Town", "Gurjiya", "Kulluwan", "Bono"],
  "Dala": ["Dala Town", "Gwammaja", "Kofar Ruwa", "Adakawa", "Kofar Mazugal", "Gobirawa"],
  "Dambatta": ["Dambatta Town", "Sansa", "Gwarabjawa", "Ajumawa"],
  "Dawakin Kudu": ["Dawakin Kudu Town", "Dawaki", "Tamburawa", "Yankatsari"],
  "Dawakin Tofa": ["Dawakin Tofa Town", "Danguguwa", "Ganduje", "Jalli"],
  "Doguwa": ["Doguwa Town", "Ragada", "Tagwaye", "Falgore"],
  "Fagge": ["Fagge Town", "Sabon Gari Kano", "Kwarin Gogau", "Wapa", "Rijiyar Lemo", "Kwarin Barau"],
  "Gabasawa": ["Yumbu", "Gabasawa Town", "Joda", "Zakirai"],
  "Garko": ["Garko Town", "Dal", "Kafin Malamai", "Gurjiya"],
  "Garun Mallam": ["Garun Mallam Town", "Chiromawa", "Jobawa", "Yalwan Yadakwari"],
  "Gaya": ["Gaya Town", "Gaya Arewa", "Wudilawa", "Balan"],
  "Gezawa": ["Gezawa Town", "Jogana", "Wangara", "Zango"],
  "Gwale": ["Gwale Town", "Gyaranya", "Dandago", "Sani Mainagge", "Dorayi"],
  "Gwarzo": ["Gwarzo Town", "Getso", "Kara", "Lakwaya"],
  "Kabo": ["Kabo Town", "Gude", "Hauwade", "Dugabau"],
  "Kano Municipal": ["Kano City", "Kofar Mata", "Shahuci", "Gandun Albasa", "Chedi", "Kankarofi", "Tudun Wazirchi"],
  "Karaye": ["Karaye Town", "Daura", "Kurugu", "Kwanyawa"],
  "Kibiya": ["Kibiya Town", "Kadigawa", "Fammar", "Unguwar Gai"],
  "Kiru": ["Kiru Town", "Badawa", "Kogo", "Ba'awa"],
  "Kumbotso": ["Kumbotso Town", "Panshekara", "Challawa", "Naibawa", "Danbare", "Kureken Sani"],
  "Kunchi": ["Kunchi Town", "Shuwaki", "Garin Sheme", "Matan Fada"],
  "Kura": ["Kura Town", "Imawa", "Rugar", "Dukawa", "Dalili"],
  "Madobi": ["Madobi Town", "Burji", "Cinkoso", "Rikadawa", "Galu"],
  "Makoda": ["Makoda Town", "Danya", "Koguna", "Bebeji Road"],
  "Minjibir": ["Minjibir Town", "Kantama", "Gandun Sarki", "Kuru"],
  "Nasarawa": ["Hotoro", "Gawuna", "Kawo", "Gama", "Giginyu", "Brigade", "Tukuntawa"],
  "Rano": ["Rano Town", "Lausu", "Zurgu", "Saji"],
  "Rimin Gado": ["Rimin Gado Town", "Butu Butu", "Dawaki", "Gulu"],
  "Rogo": ["Rogo Town", "Beli", "Falgore", "Jajaye", "Zarewa"],
  "Shanono": ["Shanono Town", "Dutsen-Bakoshi", "Faruruwa", "Kokiya"],
  "Sumaila": ["Sumaila Town", "Gani", "Gediya", "Sitti"],
  "Takai": ["Takai Town", "Bagwaro", "Fajewa", "Kachako"],
  "Tarauni": ["Tarauni Town", "Gyadi Gyadi", "Darmanawa", "Hotoro North", "Unguwar Gano"],
  "Tofa": ["Tofa Town", "Ginsawa", "Lambu", "Wangara Tofa"],
  "Tsanyawa": ["Tsanyawa Town", "Kabagiwa", "Dumbulun", "Yan Kamo"],
  "Tudun Wada": ["Tudun Wada Town", "Burum Burum", "Jandutse", "Nata'ala", "Shuwaya"],
  "Ungogo": ["Ungogo Town", "Panisau", "Rijiyar Zaki", "Kadawa", "Adaraye"],
  "Warawa": ["Warawa Town", "Jemagu", "Imawa", "Yangizo"],
  "Wudil": ["Wudil Town", "Achika", "Dankaza", "Utai", "Kausani"],

  // --- KATSINA ---
  "Bakori": ["Bakori Town", "Kakumi", "Kandarawa", "Tsiga"],
  "Batagarawa": ["Batagarawa Town", "Ajiwa", "Kwarare", "Dandagoro"],
  "Batsari": ["Batsari Town", "Wagini", "Abadau", "Yauyau"],
  "Baure": ["Baure Town", "Babban Mutum", "Garki", "Yanduna"],
  "Bindawa": ["Bindawa Town", "Dallaje", "Gaiwa", "Hididdibu"],
  "Charanchi": ["Charanchi Town", "Doka", "Banye", "Koda"],
  "Dandume": ["Dandume Town", "Mahuta", "Ilalla", "Tumbarkai"],
  "Danja": ["Danja Town", "Tandama", "Kahutu", "Tsangamawa"],
  "Dan Musa": ["Dan Musa Town", "Dan Ali", "Mara", "Mai Dabino"],
  "Daura": ["Daura Town", "Sarki Power", "Gurjiya", "Dabiramba", "Shargalle"],
  "Dutsi": ["Dutsi Town", "Dan-Ali", "Sirika", "Macimmi"],
  "Dutsin Ma": ["Dutsin Ma Town", "Kutawa", "Makera", "Shema"],
  "Faskari": ["Faskari Town", "Daudawa", "Mairuwa", "Sheme", "Yankara"],
  "Funtua": ["Funtua Town", "Dukke", "Mairuwa Funtua", "Goya", "Maigamji", "Makera Funtua"],
  "Ingawa": ["Ingawa Town", "Jobe", "Kurfeji", "Agala"],
  "Jibia": ["Jibia Town", "Mallamawa", "Yangaiya", "Magama"],
  "Kafur": ["Kafur Town", "Mahuta Kafur", "Goza", "Gozaki"],
  "Kaita": ["Kaita Town", "Baawa", "Dankaba", "Girka"],
  "Kankara": ["Kankara Town", "Mabai", "Dan Murke", "Gatakawa", "Wawar Kaza"],
  "Kankia": ["Kankia Town", "Tafashiya", "Galadima", "Rimaye"],
  "Katsina": ["Katsina Town", "Batagarawa Road", "Kofar Kaura", "Kofar Kwaya", "GRA Katsina", "Sabon Layi"],
  "Kurfi": ["Kurfi Town", "Wurma", "Barkiya", "Birchi"],
  "Kusada": ["Kusada Town", "Baure Road", "Dudunni", "Kofar Kaura Kusada"],
  "Mai'Adua": ["Mai'Adua Town", "Koza", "Danyashe", "Natsinta"],
  "Malumfashi": ["Malumfashi Town", "Karfi", "Yartali", "Makaurachi", "Burji"],
  "Mani": ["Mani Town", "Mani Road", "Duguru", "Bujawa"],
  "Mashi": ["Mashi Town", "Dogguru", "Gallu", "Jigawa Mashi"],
  "Matazu": ["Matazu Town", "Sayaya", "Mazoji", "Dissu"],
  "Musawa": ["Musawa Town", "Kira", "Gingin", "Dan Ali"],
  "Rimi": ["Rimi Town", "Abukur", "Kadandani", "Tsamiya"],
  "Sabuwa": ["Sabuwa Town", "Maibakko", "Damari", "Gamai"],
  "Safana": ["Safana Town", "Runka", "Zukana", "Babban Duhu"],
  "Sandamu": ["Sandamu Town", "Fago", "Karkarku", "Kwasarawa"],
  "Zango": ["Zango Town", "Ragada", "Yardaje", "Kawarin Kudi"],

  // --- KEBBI ---
  "Aleiro": ["Aleiro Town", "Aliero Road", "Sabiyal"],
  "Arewa Dandi": ["Arewa Town", "Dandi", "Bui", "Gumundai"],
  "Argungu": ["Argungu Town", "Matane", "Gulma", "Lailaba", "Fana"],
  "Augie": ["Augie Town", "Bayawa", "Bakin Dutse", "Dundaye"],
  "Bagudo": ["Bagudo Town", "Lafagu", "Kaoje", "Lolo"],
  "Birnin Kebbi": ["Birnin Kebbi Town", "Gulumbe", "Kardi", "Gwadangaji", "Bayawa"],
  "Bunza": ["Bunza Town", "Zogirma", "Tunga", "Maidahini"],
  "Dandi": ["Dandi Town", "Kamba", "Kyamba"],
  "Fakai": ["Mahuta", "Kangi", "Bajida", "Gulbin Kuka"],
  "Gwandu": ["Gwandu Town", "Dalijan", "Dodoru", "Malisa"],
  "Jega": ["Jega Town", "Kimba", "Dangamaji", "Basaura"],
  "Kalgo": ["Kalgo Town", "Diggi", "Gayawa", "Wuroga"],
  "Koko/Besse": ["Koko Town", "Besse", "Maikwari", "Dada"],
  "Maiyama": ["Maiyama Town", "Kawara", "Andarai", "Giwa Tazo"],
  "Ngaski": ["Ngaski Town", "Makera", "Kwakkwaba", "Wara"],
  "Sakaba": ["Sakaba Town", "Diri", "Dirin Daji", "Maza Maza"],
  "Shanga": ["Shanga Town", "Atuwo", "Dugu Tsola", "Golian"],
  "Suru": ["Dakingari", "Dani", "Aljannare", "Ginga"],
  "Wasagu/Danko": ["Ribah", "Waje", "Kanya", "Bena", "Wasagu"],
  "Yauri": ["Yauri Town", "Yelwa Yauri", "Tondi", "Zamare"],
  "Zuru": ["Zuru Town", "Dabai", "Rafin Zuru", "Senchi", "Tadurga"],

  // --- KOGI ---
  "Adavi": ["Adavi Town", "Osisi", "Kuroko", "Ikaraworo", "Nagazi"],
  "Ajaokuta": ["Ajaokuta Town", "Geregu", "Ebiya", "Ganaja", "Adogo"],
  "Ankpa": ["Ankpa Town", "Ojoku", "Abache", "Enjema", "Okaba"],
  "Bassa": ["Oguma", "Gboloko", "Ikende", "Mozum", "Sheria"],
  "Dekina": ["Dekina Town", "Anyigba", "Abocho", "Egume", "Odu", "Ojikpadala"],
  "Ibaji": ["Onyedega", "Iyano", "Ujeh", "Unale"],
  "Idah": ["Idah Town", "Ega Market Area", "Ogenigu", "Igalogba"],
  "Igalamela Odolu": ["Ajaka", "Odolu", "Oforachi", "Igalamela"],
  "Ijumu": ["Iyara", "Ogidi", "Ayere", "Okoro", "Ayegunle Gbede"],
  "Kabba/Bunu": ["Kabba Town", "Okebukun", "Aiyeteju", "Odo-Ape", "Bunu"],
  "Kogi": ["Koton Karfe", "Girinya", "Irenodu", "Chikara"],
  "Lokoja": ["Lokoja Town", "Adankolo", "Felele", "Ganaja Village", "Kabawa", "GRA Lokoja", "Lokongoma"],
  "Mopa Muro": ["Mopa", "Amuro", "Okeagi", "Ilai"],
  "Ofu": ["Ofu Town", "Ogbonicha", "Aloji", "Itakpe Ofu"],
  "Ogori/Magongo": ["Ogori", "Magongo", "Okebo"],
  "Okehi": ["Obangede", "Okehi Town", "Ohuepe", "Ihima"],
  "Okene": ["Okene Town", "Idiche", "Onyukoko", "Upogoro", "Agassa", "Bariki"],
  "Olamaboro": ["Okpo", "Imane", "Ogugu", "Emonoja", "Ugo"],
  "Omala": ["Abejukolo", "Oji Apata", "Bagaji", "Ogodu"],
  "Yagba East": ["Isanlu", "Makutu", "Ife Olukotun", "Ponyan", "Alu"],
  "Yagba West": ["Odo Ere", "Odo Egbe", "Egbe", "Okoloke", "Omi"],

  // --- KWARA ---
  "Asa": ["Afon", "Ogbondoroko", "Elebue", "Ballah", "Otte"],
  "Baruten": ["Kosubosu", "Baruten Town", "Okuta", "Gwanara", "Ilesha Baruba"],
  "Edu": ["Lafiagi", "Tsaragi", "Shonga", "Patigi Road", "Lema"],
  "Ekiti": ["Araromi Opin", "Obbo Aiyegunle", "Isolo Opin", "Osi", "Epe Opin"],
  "Ifelodun": ["Share", "Idofian", "Igbaja", "Omupo", "Amoyo", "Agbamu"],
  "Ilorin East": ["Oke Oyi", "Ilorin East Town", "Marafa", "Gambari", "Magaji Are"],
  "Ilorin South": ["Fufu", "Akanbi", "Okaka", "Oke Ogun", "Tanke", "Gaa Akanbi", "Fate"],
  "Ilorin West": ["Ilorin Town", "Adewole", "Oja Oba", "Opo Malu", "GRA Ilorin", "Tanke", "Saw Mill", "Taiwo"],
  "Irepodun": ["Omu-Aran", "Aran-Orin", "Ajase Ipo", "Rore", "Ipetu", "Esie"],
  "Isin": ["Owu Isin", "Isanlu Isin", "Iji Isin", "Oke Aba", "Alla"],
  "Kaiama": ["Kaiama Town", "Wajibe", "Gwanabe", "Bani"],
  "Moro": ["Bode Saadu", "Jebba", "Okemi", "Lanwa", "Malete"],
  "Offa": ["Offa Town", "Igosun", "Ikotun", "Ojoku", "Balogun", "Lamodi"],
  "Oke Ero": ["Oke Ero Town", "Ilofa", "Ekan Meje", "Imode", "Idofin"],
  "Oyun": ["Ilemona", "Erin Ile", "Igosun", "Ikotun Oyun", "Ipee"],
  "Pategi": ["Pategi Town", "Lade", "Kpada", "Gbugbu"],

  // --- NASARAWA ---
  "Akwanga": ["Akwanga Town", "Ningo", "Andaha", "Gudi", "Moroa"],
  "Awe": ["Awe Town", "Azara", "Kanje", "Mahanga"],
  "Doma": ["Doma Town", "Doka", "Idadu", "Rukubi", "Agwashi"],
  "Karu": ["Karu Town", "Mararaba", "Masaka", "Ado", "New Karu", "Koroduma", "Aso", "Uke"],
  "Keana": ["Keana Town", "Obi Road", "Iwagu", "Aloshbabye"],
  "Keffi": ["Keffi Town", "Angwan Lambu", "Iya", "Jigwada", "GRA Keffi"],
  "Kokona": ["Garaku", "Kokona Town", "Agwada", "Dari", "Bassa"],
  "Lafia": ["Lafia Town", "Bukan Sidi", "Shabu", "GRA Lafia", "Azuba", "Akurba"],
  "Nasarawa": ["Nasarawa Town", "Loko", "Udege", "Mararaba Udege", "Ara"],
  "Nasarawa Egon": ["Nasarawa Egon Town", "Mada Station", "Iggah", "Alizaga", "Ende"],
  "Obi": ["Obi Town", "Adudu", "Deddere", "Agwatashi", "Gidan Ausa"],
  "Toto": ["Toto Town", "Gadabuke", "Umaisha", "Kanyehu", "Gwargwada"],
  "Wamba": ["Wamba Town", "Nakere", "Arum", "Gitta", "Konvah"],

  // --- NIGER ---
  "Agaie": ["Agaie Town", "Baro", "Kintako", "Ebo"],
  "Agwara": ["Agwara Town", "Rofia", "Busuru", "Adagba"],
  "Bida": ["Bida Town", "Landzun", "Masaga", "Wadata", "Dokodza", "GRA Bida"],
  "Borgu": ["New Bussa", "Borgu Town", "Kabe", "Karabonde", "Pissa"],
  "Bosso": ["Bosso Town", "Maikunkele", "Beji", "Garatu", "Chanchaga Extension"],
  "Chanchaga": ["Minna Town", "Kpakungu", "Tudun Wada Minna", "Sauka Kahuta", "Bosso Road", "GRA Minna", "Tunga", "Dutsen Kura"],
  "Edati": ["Enagi", "Edati Town", "Gazhe", "Guzan"],
  "Gbako": ["Lemu", "Gbako Town", "Nuwankota", "Batati"],
  "Gurara": ["Gawu", "Bonu", "Izom", "Kabo", "Dikko", "Lambata"],
  "Katcha": ["Katcha Town", "Essa", "Dzwafu", "Bisasu"],
  "Kontagora": ["Kontagora Town", "Arewa", "Gabas", "Madara", "Nagwamatse"],
  "Lapai": ["Lapai Town", "Gulu", "Muye", "Evuti", "Gupa Abugi"],
  "Lavun": ["Kutigi", "Lavun Town", "Dabban", "Gbara", "Busu"],
  "Magama": ["Nasko", "Magama Town", "Ibelu", "Auna"],
  "Mariga": ["Mariga Town", "Bangi", "Igwama", "Kakihum"],
  "Mashegu": ["Mashegu Town", "Kabo", "Dapila", "Mazza"],
  "Mokwa": ["Mokwa Town", "Jaagi", "Rabba", "Kudu", "Bokani", "Muwo"],
  "Munya": ["Sarkin Pawa", "Kuchi", "Dangunu", "Guni", "Fuka"],
  "Paikoro": ["Paikoro Town", "Paiko", "Chimbi", "Kwagana", "Adunu"],
  "Rafi": ["Kagara", "Rafi Town", "Guna", "Kusherki", "Tegina"],
  "Rijau": ["Rijau Town", "Dukku", "Genu", "Shambo"],
  "Shiroro": ["Kuta", "Shiroro Town", "Gurmana", "Egwada", "Pina", "Kato"],
  "Suleja": ["Suleja Town", "Bagama", "Magajiya", "Hashimi", "Moro", "Kwamba", "Buru"],
  "Tafa": ["Wuse Tafa", "Ija-Gwari", "New Bwari", "Dogon Kurmi", "Garam"],
  "Wushishi": ["Wushishi Town", "Akare", "Lokogoma", "Kwata", "Zungeru"],

  // --- OGUN ---
  "Abeokuta North": ["Akomoje", "Ibara Orile", "Imala", "Olorunda", "Lafenwa", "Ita Iyalode"],
  "Abeokuta South": ["Ake", "Ijaiye", "Ago Oko", "Itoku", "Adatan", "Isale Igbein", "Ibara GRA"],
  "Ado-Odo/Ota": ["Ota Town", "Ado-Odo", "Igbesa", "Agbara", "Sango Ota", "Iju Ota", "Itele", "Atan Ota", "Owode"],
  "Egbado North": ["Ayetoro", "Imasai", "Igbogila", "Joga Orile", "Iboro"],
  "Egbado South": ["Ilaro", "Ilobi", "Erinja", "Oke-Odan", "Iwoye"],
  "Ewekoro": ["Itori", "Ewekoro Town", "Lapeleke", "Wasimi", "Abalabi", "Elere"],
  "Ifo": ["Ifo Town", "Agbado", "Akute", "Alagbole", "Ope Ilu", "Matogun", "Lambe", "Ibara Orile Ifo"],
  "Ijebu East": ["Ogbere", "Ijebu Ife", "Itele Ijebu", "Imobi"],
  "Ijebu North": ["Ijebu Igbo", "Oru Ijebu", "Ago Iwoye", "Awa", "Mamu"],
  "Ijebu North East": ["Atan Ijebu", "Ilese", "Odosenlu", "Igan Road"],
  "Ijebu Ode": ["Ijebu Ode Town", "Ilegbe", "Isiwo", "Obalende Ijebu", "Imoru"],
  "Ikenne": ["Ikenne Town", "Iperu", "Ogere", "Ilisan", "Irolu"],
  "Imeko Afon": ["Imeko", "Afon", "Ilara", "Agberiodo"],
  "Ipokia": ["Ipokia Town", "Idiroko", "Ihunbo", "Agosasa", "Tube", "Maun"],
  "Obafemi Owode": ["Owode Egba", "Mokoloki", "Obafemi", "Ofada", "Ajebo", "Ogere Road", "Siun"],
  "Odogbolu": ["Odogbolu Town", "Ayepe", "Ijesa Ijebu", "Okun Owa", "Ososa"],
  "Odeda": ["Odeda Town", "Alabata", "Obantoko", "Agbogbo", "Bode Olude"],
  "Ogun Waterside": ["Abigi", "Iwopin", "Efire", "Ayila", "Lukogbe"],
  "Remo North": ["Isara", "Ipara", "Ilara", "Akaka"],
  "Sagamu": ["Sagamu Town", "Ogijo", "Sotubo", "Araromi", "Offin", "Simawa", "Agbowa", "Mosan"],

  // --- ONDO ---
  "Akoko North-East": ["Ikare Akoko", "Iboropa", "Akor", "Iyame", "Eshada"],
  "Akoko North-West": ["Oke Agbe", "Arigidi", "Ogbagi", "Ajowa", "Ikaram", "Ase"],
  "Akoko South-West": ["Oka Akoko", "Oba Akoko", "Supare", "Ipe", "Afo"],
  "Akoko South-East": ["Isua Akoko", "Epimi", "Ifira", "Ipe Akoko"],
  "Akure North": ["Iju", "Ita Ogbolu", "Ogbese", "Ilado", "Oba-Ile"],
  "Akure South": ["Akure Town", "Alagbaka", "Ilesha Road", "Oke-Aro", "Ijoka", "Oshinle", "Agbogbo", "Odopetu", "Ijapo Estate", "Oluwatuyi"],
  "Ese Odo": ["Igbekebo", "Arogbo", "Kiribo", "Igbotu", "Inikorogha"],
  "Idanre": ["Idanre Town", "Atosin", "Alade", "Isalu", "Owena"],
  "Ifedore": ["Igbara Oke", "Ilara Mokin", "Ibule Soro", "Isarun", "Ero"],
  "Ilaje": ["Igbokoda", "Mahin", "Ugbo", "Aheri", "Etikan"],
  "Ile Oluji/Okeigbo": ["Ile Oluji", "Okeigbo", "Ogotun Road", "Awo", "Bombata"],
  "Irele": ["Ode Irele", "Ajagba", "Akotogbo", "Omi Iyasan"],
  "Odigbo": ["Ore", "Odigbo Town", "Agbabu", "Lafe", "Oniparaga", "Araromi Obu"],
  "Okitipupa": ["Okitipupa Town", "Ikoya", "Ayeka", "Igbotako", "Ilutitun", "Erinje"],
  "Ondo East": ["Bolorunduro", "Asante", "Fagbo", "Oboto"],
  "Ondo West": ["Ondo Town", "Bagbe", "Laje", "Litaye", "Yaba Ondo", "Ifon Road"],
  "Ose": ["Ifon", "Owo Ose Area", "Imoru", "Arimogija", "Ute", "Imeri"],
  "Owo": ["Owo Town", "Emure Ile", "Isuada", "Ipele", "Ijebu Owo", "Uso", "Igboroko"],

  // --- OSUN ---
  "Atakunmosa East": ["Iperindo", "Igangan", "Ila Aje", "Alapata"],
  "Atakunmosa West": ["Osú", "Ibodi", "Igbo Ije", "Ifewara"],
  "Aiyedaade": ["Gbongan", "Ode Omu", "Orile Owu", "Oji"],
  "Aiyedire": ["Ile Ogbo", "Oke Osun", "Kuta", "Oluwu"],
  "Boluwaduro": ["Otan-Ayegbaju", "Eripa", "Igbajo", "Oke-Run"],
  "Boripe": ["Iragbiji", "Ada", "Iree", "Aagba", "Ororuwo"],
  "Ede North": ["Oja Timi", "Olodan", "Babanla", "Alusekere", "Apaso"],
  "Ede South": ["Kuye", "Loogun", "Jagun", "Sekona"],
  "Egbedore": ["Awo", "Iragberi", "Ara", "Ojo-Aro", "Ofatedo"],
  "Ejigbo": ["Ejigbo Town", "Isundunrin", "Ifon Osun", "Ola", "Ilawo"],
  "Ife Central": ["Ife Town", "Enuwa", "Moore", "Ilare", "Iremo", "Lagere", "Parakin Estate"],
  "Ife East": ["Modakeke", "Yekemi", "Aba Coker", "Oyere"],
  "Ife North": ["Ipetumodu", "Edunabon", "Moro", "Yakoyo", "Asipa"],
  "Ife South": ["Ifetedo", "Garage Olode", "Aye", "Oke Owena"],
  "Ifedayo": ["Oke-Ila", "Ora Igbomina", "Oba-Aleku"],
  "Ifelodun": ["Ikirun", "Iba", "Obagun", "Obaagun", "Eko-Ende"],
  "Ila": ["Ila Orangun", "Oyi Ayegunle", "Oke Ola"],
  "Ilesa East": ["Bolorunduro Ilesa", "Isokun", "Upper Area", "Ilaje Ilesa"],
  "Ilesa West": ["Ereja", "Isokun West", "Ijamo", "Iloro"],
  "Irepodun": ["Ilobu", "Erin Osun", "Ifon Osun", "Ifon Road"],
  "Irewole": ["Ikire", "Iwara", "Odeyinka", "Gbengbeleku"],
  "Isokan": ["Apomu", "Ikoyi Osun", "Idominasi"],
  "Iwo": ["Iwo Town", "Molete", "Oke Adan", "Agbowo", "Gidigbo"],
  "Obokun": ["Ibokun", "Ilare", "Esa Oke", "Iponda", "Ada-Owode"],
  "Odo Otin": ["Okuku", "Inisa", "Ekusa", "Ijabe", "Ekosin", "Oyan"],
  "Ola Oluwa": ["Bode Osi", "Ilemowu", "Ikonifin", "Ajagunlase"],
  "Olorunda": ["Igbona", "Ota Efun", "Oke Baale", "Olorunda Area", "Owode Ilesa Road"],
  "Oriade": ["Ijebu Jesa", "Eri Ijesa", "Ipetu Ijesa", "Ikeji Arakeji", "Iwoye Ijesa"],
  "Orolu": ["Ifon Osun Orolu", "Olufon Area", "Bolajoko"],
  "Osogbo": ["Osogbo Town", "Oke Baale", "Oja Oba", "Alekuwodo", "Dada Estate", "Oke Fia", "GRA Osogbo", "Olorunda Osogbo"],

  // --- OYO - rest already above ---

  // --- PLATEAU ---
  "Barkin Ladi": ["Barkin Ladi Town", "Gashish", "Gassa", "Marit"],
  "Bassa": ["Bassa Town", "Buhit", "Mafara", "Miango", "Kwall"],
  "Bokkos": ["Bokkos Town", "Daffo", "Mushere", "Sha", "Richa"],
  "Jos East": ["Angware", "Fobur", "Shere", "Federe", "Maijuju"],
  "Jos North": ["Jos Town", "Terminus", "Gangare", "Rukuba Road", "Tina Junction", "Angwan Rogo", "Kabong", "Nasarawa Gwong", "GRA Jos"],
  "Jos South": ["Bukuru", "Du", "Gyel", "Kuru", "Shen", "Vom", "Zawan", "Rayfield", "Rantya"],
  "Kanam": ["Dengi", "Kanam Town", "Kunkyam", "Jarmai"],
  "Kanke": ["Amper", "Kanke Town", "Kabwir", "Amper"],
  "Langtang North": ["Langtang Town", "Pilat Gani", "Pishe", "Nyer"],
  "Langtang South": ["Mabudi", "Langtang South Town", "Dadin Kowa", "Timbol"],
  "Mangu": ["Mangu Town", "Panyam", "Gindiri", "Kerang", "Mangal", "Chakfem"],
  "Mikang": ["Tunkus", "Mikang Town", "Garkawa", "Koenoem"],
  "Pankshin": ["Pankshin Town", "Chip", "Fier", "Lankan", "Kadung"],
  "Qua'an Pan": ["Baap", "Kurgwi", "Kwalla", "Namus"],
  "Riyom": ["Riyom Town", "Attakar", "Bum", "Jol", "Ganawuri"],
  "Shendam": ["Shendam Town", "Derteng", "Kalong", "Yelwa Shendam"],
  "Wase": ["Wase Town", "Kadarko", "Lamba", "Mavo", "Gudus"],

  // --- SOKOTO ---
  "Binji": ["Binji Town", "Bunkari", "Inname", "Maikulki"],
  "Bodinga": ["Bodinga Town", "Badau", "Baga", "Danchadi"],
  "Dange Shuni": ["Dange", "Shuni", "Tuntube", "Rikina"],
  "Gada": ["Gada Town", "Kaffe", "Kyadawa", "Kadassaka"],
  "Goronyo": ["Goronyo Town", "Boyi", "Giyawa", "Kojiyo"],
  "Gudu": ["Balle", "Gudu Town", "Kurmanawa", "Bachaka"],
  "Gwadabawa": ["Gwadabawa Town", "Gidan Kaya", "Gigane", "Salame"],
  "Illela": ["Illela Town", "Damba", "Gada Labbo", "Kalmalo"],
  "Isa": ["Isa Town", "Turba", "Bargaja", "Tidibale"],
  "Kebbe": ["Kebbe Town", "Fakku", "Kuchi", "Ungushi"],
  "Kware": ["Kware Town", "Gagi", "Durbawa", "Hamma Ali"],
  "Rabah": ["Rabah Town", "Gandi", "Riji", "Gwaddodi"],
  "Sabon Birni": ["Sabon Birni Town", "Lajinge", "Tsamaye", "Unguwar Lalle"],
  "Shagari": ["Shagari Town", "Dandin Mahe", "Horo Birni", "Jaredi"],
  "Silame": ["Silame Town", "Labani", "Katami", "Gande"],
  "Sokoto North": ["Sokoto Town", "Kanwuri", "Magajin Rafi", "Waziri B", "Kofar Atiku"],
  "Sokoto South": ["Sokoto South Town", "Tudun Wada Sokoto", "Gagi", "Arkilla", "Rijiyar Dorowa"],
  "Tambuwal": ["Tambuwal Town", "Bakaya", "Dogon Daji", "Faga", "Jabo"],
  "Tangaza": ["Tangaza Town", "Sakkwai", "Magonho", "Sutule"],
  "Tureta": ["Tureta Town", "Barayar Giwa", "Duma", "Fura Girke"],
  "Wamako": ["Wamako Town", "Kalambaina", "Gumbi", "Gidan Buba", "Wajake"],
  "Wurno": ["Wurno Town", "Achida", "Chacho", "Kwargaba"],
  "Yabo": ["Yabo Town", "Kilgori", "Fakka", "Bingaje"],

  // --- TARABA ---
  "Ardo Kola": ["Sunkani", "Ardo Kola Town", "Lamurde Kola", "Iware"],
  "Bali": ["Bali Town", "Badakoshi", "Gang Dole", "Musa Jauro", "Mai Hula"],
  "Donga": ["Donga Town", "Akate", "Fada", "Gindin Waya", "Mararaba Donga"],
  "Gashaka": ["Serti", "Gashaka Town", "Mayo Selbe", "Garbabi"],
  "Gassol": ["Mutum Biyu", "Gassol Town", "Tutare", "Sarkin Shira", "Wuryo"],
  "Ibi": ["Ibi Town", "Dampar", "Sarkin Kudu", "Rafin Sanye"],
  "Jalingo": ["Jalingo Town", "Turaki", "Barade", "Kona", "Sarkin Dawaki", "Mile Six"],
  "Karim Lamido": ["Karim Lamido Town", "Amar", "Bikwin", "Jen Ardido", "Muri"],
  "Kumi": ["Baissa", "Bissaula", "Gidan Achini"],
  "Lau": ["Lau Town", "Garau", "Kunini", "Lau Habe", "Mayo Lope"],
  "Sardauna": ["Gembu", "Sardauna Town", "Mbamga", "Nguroje", "Titong", "Kabri"],
  "Takum": ["Takum Town", "Dutse", "Fete", "Bikaten", "Shibong"],
  "Ussa": ["Lissam", "Ussa Town", "Kpambo", "Rufin Kwarra"],
  "Wukari": ["Wukari Town", "Hospital Road", "Puje", "Avyi", "Bantaje"],
  "Yorro": ["Pantisawa", "Yorro Town", "Lankaviri", "Pupule"],
  "Zing": ["Zing Town", "Monkin", "Yakoko", "Bitako", "Zing Township"],

  // --- YOBE ---
  "Bade": ["Gashua", "Bade Town", "Zangon Musa", "Dagona", "Sugum"],
  "Bursari": ["Dapchi", "Bursari Town", "Bayamari", "Guba"],
  "Damaturu": ["Damaturu Town", "Nayi Nawa", "Bindigari", "Maisandari", "Gujba Road", "Pawari", "GRA Damaturu"],
  "Fika": ["Fika Town", "Gadaka", "Goniri", "Fusami", "Dozi"],
  "Fune": ["Damagum", "Fune Town", "Daura Fune", "Ngarnam", "Dogo Maikaho"],
  "Geidam": ["Geidam Town", "Kelluri", "Futchimiram", "Balle"],
  "Gujba": ["Buni Yadi", "Gujba Town", "Buni Gari", "Wagir"],
  "Gulani": ["Bara", "Gulani Town", "Gagure", "Ruhu"],
  "Jakusko": ["Jakusko Town", "Jaba", "Muguram", "Zabudum"],
  "Karasuwa": ["Jajimaji", "Karasuwa Town", "Bukar", "Bukarti"],
  "Machina": ["Machina Town", "Dole", "Falam"],
  "Nangere": ["Nangere Town", "Chukuriwa", "Dawasa", "Tikau"],
  "Nguru": ["Nguru Town", "Kasuwa Nguru Area", "Bulanguwa", "Madiya"],
  "Potiskum": ["Potiskum Town", "Bole", "Dogo Nini", "Mamudo", "Lailai", "Arikime"],
  "Tarmuwa": ["Babangida", "Tarmuwa Town", "Babbangida", "Koka"],
  "Yunusari": ["Kanamma", "Yunusari Town", "Mozagun", "Dekwa"],
  "Yusufari": ["Yusufari Town", "Gumsa", "Maimala", "Tulo Tulo"],

  // --- ZAMFARA ---
  "Anka": ["Anka Town", "Bagega", "Dan Galadima", "Magaji"],
  "Bakura": ["Bakura Town", "Dakko", "Damri", "Yar Gaya"],
  "Birnin Magaji/Kiyaw": ["Birnin Magaji", "Kiyaw", "Gora", "Nasara"],
  "Bukkuyum": ["Bukkuyum Town", "Gwashi", "Ruwan Jema", "Zarah"],
  "Bungudu": ["Bungudu Town", "Bela", "Furu Girke", "Gada", "Nahuche"],
  "Gummi": ["Gummi Town", "Gyalange", "Gayari", "Illela Gummi"],
  "Gusau": ["Gusau Town", "Mada", "Wanke", "Galadima", "Sabon Gari Gusau", "GRA Gusau", "Tudun Wada Gusau"],
  "Kaura Namadi": ["Kaura Namadi Town", "Yankaba", "Kyambarawa", "Sakajiki"],
  "Maradun": ["Maradun Town", "Dosara", "Gora Namaye", "Faru"],
  "Maru": ["Maru Town", "Dansadau", "Kanoma", "Mayanchi", "Birnin Magaji Maru"],
  "Shinkafi": ["Shinkafi Town", "Badarawa", "Galadi", "Jangeru"],
  "Talata Mafara": ["Talata Mafara Town", "Jangebe", "Morai", "Ruwan Bore", "Garbadu"],
  "Tsafe": ["Tsafe Town", "Bilbis", "Daukoshi", "Keta", "Yankuzo"],
  "Zurmi": ["Zurmi Town", "Dauran", "Gurbin Bore", "Kashin Zama", "Kawla"],

  // --- KEBBI, KOGI, KWARA, NASARAWA, NIGER, OGUN, ONDO, OSUN ALREADY COVERED ABOVE WITH BASE ---
  "Aleiro": ["Aleiro Town"],
  "Arewa Dandi": ["Arewa", "Dandi"],
  "Argungu": ["Argungu Town", "Alwasa", "Kokani"],
  "Augie": ["Augie Town"],
  "Bagudo": ["Bagudo Town", "Tuga", "Kaoje"],
  "Birnin Kebbi": ["Birnin Kebbi Town", "Gulumbe", "Makera"],
  "Bunza": ["Bunza Town"],
  "Dandi": ["Kamba", "Dandi Town"],
  "Fakai": ["Mahuta"],
  "Gwandu": ["Gwandu Town"],
  "Jega": ["Jega Town", "Kimba"],
  "Kalgo": ["Kalgo Town"],
  "Koko/Besse": ["Koko", "Besse"],
  "Maiyama": ["Maiyama Town"],
  "Ngaski": ["Wara", "Ngaski Town", "Makarin"],
  "Sakaba": ["Dirin Daji", "Sakaba Town"],
  "Shanga": ["Shanga Town"],
  "Suru": ["Dakingari"],
  "Wasagu/Danko": ["Ribah", "Wasagu", "Danko"],
  "Yauri": ["Yauri Town", "Yelwa"],
  "Zuru": ["Zuru Town"],

  // fallback for any missing LGA
  "Onuimo": ["Okwe", "Okwele"],
};
