export const agentReviews= [
  {
    id: "review_1",
    agentId: "agent_123",
    userId: "user_789",
    inspectionId: "inspection_222",
    rating: 5,
    comment: "Very professional and honest",
    createdAt: "2026-05-11T10:00:00Z"
  }, 
    {
    id: "review_2",
    agentId: "agent_123",
    userId: "user_456",
    inspectionId: "inspection_333",
    rating: 4,
    comment: "Good communication but the property was not as described",
    createdAt: "2026-05-12T14:30:00Z"
  }
]

export const LazyHomeReviews = [
  {
    id: "review_1",
    agentId: "agent_123",
    userId: "user_789",
    inspectionId: "inspection_222",
    rating: 5,
    comment: "Very professional and honest",
    createdAt: "2026-05-11T10:00:00Z"
  }, 
    {
    id: "review_2",
    agentId: "agent_123",
    userId: "user_456",
    inspectionId: "inspection_333",
    rating: 4,
    comment: "Good communication but the property was not as described",
    createdAt: "2026-05-12T14:30:00Z"
  }
]

export const mockUser = [
    {
        id: 1,
        name: 'Tunde Adebayo',
        agency: 'Prime Estates',
        location: 'Lekki, Lagos',
        avatar: 'https://i.pravatar.cc/150?img=5',
        averageRating: 4.6,
    totalRatings: 27,
        verified: true,
    },
    {
        id: 2,
        name: 'Sade Alabi',
        agency: 'Luxury Homes',
        location: 'Victoria Island, Lagos',
        avatar: 'https://i.pravatar.cc/150?img=8',
        averageRating: 4.6,
    totalRatings: 27,
        verified: true,
    },
    {
        id: 3,
        name: 'Kehinde Ogunleye',
        agency: 'Elite Properties',
        location: 'Ikoyi, Lagos',
        avatar: 'https://i.pravatar.cc/150?img=12',
        averageRating: 4.6,
    totalRatings: 27,
        verified: true,
    },
];

export const mockProperties = [
    {
        id: 1,
        listedBy: mockUser[0].id,
        title: '3 Bedroom Duplex in Lekki Phase 1',
        propertyType: 'Duplex',
        Description: "Spacious 3 bedroom duplex with modern amenities in the heart of Lekki Phase 1. Features a private swimming pool, gym, and 24/7 security. Perfect for families looking for comfort and convenience.",
        size: 250,
        price: 2500000,
        pricePer: 'year',
        location: 'Lekki Phase 1, Lagos',
        StreetAddress: '12 Palm Street',
        cityORArea: "Lekki Phase 1",
        State: "Lagos State",
        nearbyLandmarks: 'Lekki Mall, Novare Lekki Mall, Lekki Conservation Centre',
        bedrooms: 3,
        bathrooms: 4,
        Amenities: ['Swimming Pool', 'Gym', '24/7 Security', 'Power Backup'],
        status: 'inactive',
        approved: true,
        featured: true,
        verified: true,
        rentPaid: true,
        rentPaidBy: mockUser[0].id,
        paymentDate: new Date(2026, 1, 5).toISOString(),
        image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
        date: new Date(2026, 1, 5).toISOString(),
    },
    {
        id: 2,
        listedBy: mockUser[1].id,
        title: '2 Bedroom Apartment in Victoria Island',
        price: 3200000,
        location: 'Victoria Island, Lagos',
        StreetAddress: '12 Palm Street',
        cityORArea: "Lekki Phase 1",
        State: "Lagos State",
        nearbyLandmarks: 'Lekki Mall, Novare Lekki Mall, Lekki Conservation Centre',
        bedrooms: 2,
        bathrooms: 3,
        Amenities: ['Gym', '24/7 Security', 'Power Backup'],
        status: 'active',
        approved: true,
        featured: false,
        verified: true,
        rentPaid: false,
        rentPaidBy: null,
        paymentDate: null,
        image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
        date: new Date(2026, 1, 10).toISOString(),
    },
    {
        id: 3,
        listedBy: mockUser[2].id,
        title: '4 Bedroom Detached House in Ikoyi',
        price: 5000000,
        location: 'Ikoyi, Lagos',
        StreetAddress: '12 Palm Street',
        cityORArea: "Lekki Phase 1",
        State: "Lagos State",
        nearbyLandmarks: 'Lekki Mall, Novare Lekki Mall, Lekki Conservation Centre',
        bedrooms: 4,
        bathrooms: 5,
        Amenities: ['Swimming Pool', 'Gym', '24/7 Security', 'Power Backup', 'Garden'],
        status: 'inactive',
        approved: false,
        featured: false,
        verified: false,
        rentPaid: false,
        rentPaidBy: null,
        paymentDate: null,
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
        date: new Date(2026, 1, 15).toISOString(),
    },
];

export const testimonials = [
    {
        name: 'Chidi Okonkwo',
        location: 'Lekki, Lagos',
        avatar: 'https://i.pravatar.cc/150?img=12',
        text: 'I was scared of online payment but LazyHomes escrow made me feel safe. My money stayed protected until I saw the house!',
    },
    {
        name: 'Amina Bello',
        location: 'Ikoyi, Lagos',
        avatar: 'https://i.pravatar.cc/150?img=45',
        text: 'No more fraud! I got my full refund when the property was different from photos. Best decision ever.',
    },
];



export const mockInspections = [
    {
        id: 1,
        title: "Inspection Scheduled",
        preferredDate: new Date(2026, 1, 7, 10, 0).toISOString(),
        alternativeDate: new Date(2026, 1, 8, 10, 0).toISOString(),
        visitors: 2,
        fullName: 'John Doe',
        phone: '+2348012345678',
        email: 'john.doe@example.com',
        specialRequests: 'Please call me before the inspection.',
        requestStatus: 'pending',
        status: 'Upcoming' || "cancelled" || "completed" || "inprogress",
        propertyId: mockProperties[0].id,
        feedbackType: 'complaint',
        photo: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
        comments: 'I was promised a 3 bedroom duplex but the agent showed me a 2 bedroom apartment. Very disappointed.',
        feedbackTimestamp: new Date().toISOString(),
        rentPaid: false,
        paymentDate: null,
    },
    {
        id: 2,
        title: "Payment in Escrow",
        preferredDate: new Date(2026, 2, 7, 10, 0).toISOString(),
        alternativeDate: new Date(2026, 2, 8, 10, 0).toISOString(),
        visitors: 1,
        fullName: 'Jane Smith',
        phone: '+2348098765432',
        email: 'jane.smith@example.com',
        specialRequests: 'I have a mobility issue, please ensure the property is accessible.',
        requestStatus: 'pending',
        status: 'Pending',
        propertyId: mockProperties[1].id,
        feedbackType: 'proceed',
        photo: ' https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
        comments: ' The property was exactly as advertised and the agent was very helpful. I am proceeding with the purchase.',
        feedbackTimestamp: new Date().toISOString(),
        rentalAgreementUrl: 'https://example.com/rental-agreement.pdf',
        rentPaid: true,
        paymentDate: new Date().toISOString(),
    },
    {
        id: 2,
        title: "Rental Agreement",
        preferredDate: new Date(2026, 2, 7, 14, 30).toISOString(),
        alternativeDate: new Date(2026, 2, 8, 14, 30).toISOString(),
        visitors: 1,
        fullName: 'Jane Smith',
        phone: '+2348098765432',
        email: 'jane.smith@example.com',
        specialRequests: 'I have a mobility issue, please ensure the property is accessible.',
        requestStatus: 'Accepted',
        status: 'completed',
        propertyId: mockProperties[2].id,
        feedbackType: 'rejected',
        photo: ' https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
        comments: ' the landlord refused to accept me after interview and was very rude. ',
        feedbackTimestamp: new Date().toISOString(),
        rentalAgreementUrl: 'https://example.com/rental-agreement.pdf',
        rentPaid: true,
        paymentDate: new Date().toISOString(),

    },
];

